### ISSUE TITLE
Shortcut for saving

### ISSUE THREAD

**Issue by laraning** [itainathaniel/nova-admin-notes#1]
Hi,

Good package, thank you! Small, enhancement, is it possible to add a CTRL+ENTER shortcut to automatically save the notes (so i dont need to go all the time to the save button) ?

Also, on my computer de textarea passes the height of the screen, meaning I always needs to scroll down to get on the "save" button. Maybe there is a better Tailwind CSS class that can help identifying the textarea with a better height... 

Cheers!
Bruno.

**Comment by itainathaniel** [comment]
Thanks for the ideas, i'll look into them!

**Comment by itainathaniel** [comment]
Hi, please see latest [release 1.0.2](https://github.com/itainathaniel/nova-admin-notes/releases/tag/1.0.2).

Instead of keyboard shortcut I implemented an autosave functionality, and of course fixed the textarea's height.

**Comment by laraning** [comment]
Great! thanks! Keep up the good work :)
